#!/bin/sh
# DPML system bootstrap scrip.
#

executeAnt()
{
    STATUS=99
    while [ "$STATUS" -eq 99 ] ; do
      ant -Ddpml.signature=BOOTSTRAP "$@"
      STATUS="$?"
    done
    if [ "$STATUS" == 0 ] ; then
        echo ""
    else
        exit 1
    fi
}

dpmlLibrary()
{
    cd depot/library
    executeAnt -f bootstrap.xml clean install
    cd ../..
}

dpmlPart()
{
    cd metro/part
    executeAnt -f bootstrap.xml clean install
    cd ../..   
}

dpmlTransit()
{
    cd transit/core
    executeAnt -f bootstrap.xml clean install
    cd ../..   
}

dpmlCli()
{
    cd util/cli
    executeAnt -f bootstrap.xml clean install
    cd ../..   
}

dpmlBuild()
{
    cd depot/build
    executeAnt -f bootstrap.xml clean install
    cd ../..   
}

dpmlTools()
{
    cd depot/tools
    executeAnt -f bootstrap.xml clean install
    cd ../..   
}

dpmlExternal()
{
    cd external
    build clean install
    cd ..
}

dpmlTransit
dpmlPart
dpmlLibrary
dpmlCli
dpmlBuild
dpmlTools
dpmlExternal

echo "BOOTSTRAP SUCCESSFUL"


