#!/bin/sh
#
# Utility script that executes the bootstrap build.
#
# The following command will bootstrap using the SNAPSHOT version identifier.
#
# $ bootstrap
#
# Versioned builds can be invoked using the following command (where '123' is the version to build):
# 
# $ bootstrap 123
#

build()
{
    STATUS=99
    while [ "$STATUS" -eq 99 ] ; do
      if [ -n "$ID" ] ; then
        BUILD_ID="-Dbuild.signature=$ID"
      else
        BUILD_ID=""
      fi
      echo "building project with release ID [$ID]"
      ant $BUILD_ID "$@"
      STATUS="$?"
    done
    if [ "$STATUS" == 0 ] ; then
        echo ""
    else
        exit 1
    fi
}

antlibCleanup()
{
    # need something in here to delete dpml content in .ant/lib
}

transitMain()
{
    cd transit/core
    build clean install
    cd ../..
}

transitTools()
{
    cd transit/tools
    build clean install
    cd ../..
}

depotLibrary()
{
    cd depot/library/common
    build clean install
    cd ../../..
}

depotAntBuilder()
{
    cd depot/tools/builder
    build clean install
    cd ../../..
}

externalModules()
{
    cd external
    build clean install
    cd ..
}

utilCli()
{
    cd util/cli
    build clean install
    cd ../..
}

depotLibraryConsole()
{
    cd depot/library/console
    build clean install
    cd ../../..
}

depotCoreConsole()
{
    cd depot/core/console
    build clean bootstrap
    cd ../../..
}

ID=$1
antlibCleanup
transitMain
transitTools
depotLibrary
depotAntBuilder
externalModules
utilCli
depotLibraryConsole
depotCoreConsole
