<?xml version="1.0" encoding="ISO-8859-1"?>

<module uri="artifact:module:dpml/transit/dpml-transit#@PROJECT-VERSION@">

  <header>
    <publisher name="The Digital Product Meta Library"/>
    <packages>
      <package name="net.dpml.transit"/>
      <package name="net.dpml.transit.artifact"/>
      <package name="net.dpml.transit.link"/>
      <package name="net.dpml.transit.local"/>
      <package name="net.dpml.transit.model"/>
      <package name="net.dpml.transit.monitor"/>
      <package name="net.dpml.transit.registry"/>
      <package name="net.dpml.transit.store"/>
      <package name="net.dpml.transit.tools"/>
      <package name="net.dpml.transit.util"/>
    </packages>
    <home href="http://www.dpml.net/transit"/>
    <docs href="http://www.dpml.net"/>
    <legal>
      <license href="http://www.dpml.net/about/legal/license.html"/>
      <notice href="http://www.dpml.net/about/legal/notice.html"/>
    </legal>
    <svn href="svn://svn.berlios.de/dpml/trunk/main/transit"/>
    <repository href="http://repository.dpml.net/classic"/>
  </header>

  <resources>

    <!-- module resources -->

    <resource key="dpml-transit-main">
      <info>
        <group>dpml/transit</group>
        <name>dpml-transit-main</name>
        <version>@PROJECT-VERSION@</version>
        <types>
          <type name="jar"/>
        </types>
      </info>
    </resource>

    <resource key="dpml-transit-tools">
      <info>
        <group>dpml/transit</group>
        <name>dpml-transit-tools</name>
        <version>@PROJECT-VERSION@</version>
        <types>
          <type name="jar"/>
        </types>
      </info>
      <dependencies>
        <include key="dpml-transit-main"/>
        <include key="ant"/>
      </dependencies>
    </resource>

    <resource>
      <info>
        <group>junit</group>
        <name>junit</name>
        <version>3.8.1</version>
        <types>
          <type name="jar"/>
        </types>
      </info>
    </resource>

    <resource key="ant">
      <info>
        <group>ant</group>
        <name>ant</name>
        <version>@COMMON-ANT-VERSION@</version>
        <types>
          <type name="jar"/>
        </types>
      </info>
    </resource>

    <resource>
      <info>
        <group>ant</group>
        <name>ant-junit</name>
        <version>@COMMON-ANT-VERSION@</version>
        <types>
          <type name="jar"/>
        </types>
      </info>
      <dependencies>
        <include key="junit" />
        <include key="ant" />
      </dependencies>
    </resource>

  </resources>

</module>

